// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Gleam contributors

use arbitrary::{Arbitrary, Result, Unstructured};

#[derive(Debug, Clone, PartialEq, Eq)]
enum Ty {
    Int,
    Float,
    Str,
    Bool,
    ListInt,
    Tup(Box<Ty>, Box<Ty>),
    Custom(usize),
    BitArray,
}

#[derive(Debug, Clone)]
struct Ctor {
    name: String,
    fields: Vec<(Option<String>, Ty)>,
}

#[derive(Debug, Clone)]
pub struct CustomType {
    name: String,
    ctors: Vec<Ctor>,
}

#[derive(Debug, Clone)]
struct FnSig {
    name: String,
    params: Vec<(String, Ty)>,
    ret: Ty,
}

#[derive(Debug, Clone)]
pub enum Expr {
    IntLit(i64),
    FloatLit(f64),
    StrLit(&'static str),
    BoolLit(bool),
    Var(String),
    ListLit(Vec<Expr>),
    TupLit(Box<Expr>, Box<Expr>),
    Bin(BinOp, Box<Expr>, Box<Expr>),
    NegBool(Box<Expr>),
    NegInt(Box<Expr>),
    Case {
        subjs: Vec<Expr>,
        clauses: Vec<Clause>,
    },
    Block(Vec<(String, Expr)>, Box<Expr>),
    Call {
        name: String,
        args: Vec<Expr>,
    },
    Pipe {
        first: Box<Expr>,
        name: String,
        args: Vec<Expr>,
    },
    ApplyAnon {
        params: Vec<String>,
        body: Box<Expr>,
        args: Vec<Expr>,
    },
    BitsLit(Vec<BitSeg>),
}

/// A segment of a bit-array literal (`<<...>>`).
#[derive(Debug, Clone)]
pub enum BitSeg {
    /// `<<value:width>>` - a fixed-width integer segment.
    Int(u32, u8),
    /// `<<"str":utf8>>` - a UTF-8 string segment.
    Utf8(&'static str),
}

#[derive(Debug, Clone, Copy)]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Rem,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Or,
    Concat,
    /// Float arithmetic (`+. -. *. /.`) and comparison (`>. >=. <. <=.`).
    FAdd,
    FSub,
    FMul,
    FDiv,
    FGt,
    FGe,
    FLt,
    FLe,
}

#[derive(Debug, Clone)]
pub struct Clause {
    pats: Vec<Pattern>,
    alts: Vec<Pattern>,
    guard: Option<Expr>,
    body: Expr,
}

#[derive(Debug, Clone)]
enum Pattern {
    Discard,
    Var(String),
    Alias(Box<Pattern>, String),
    IntLit(u32),
    FloatLit(f64),
    StrLit(&'static str),
    BoolLit(bool),
    Prefix(&'static str, Option<String>),
    ListNil,
    ListCons { elems: Vec<Pattern>, rest: RestPat },
    CtorPat { name: String, fields: Vec<Pattern> },
    TupPat(Box<Pattern>, Box<Pattern>),
    Bits(Vec<BitSegPat>),
}

#[derive(Debug, Clone)]
struct IntOpt {
    width: u8,
    big: bool,
    signed: bool,
}

#[derive(Debug, Clone)]
enum BitSegPat {
    /// `<<value:width>>` - literal integer segment.
    IntLit(u32, u8),
    /// `<<"str":utf8>>` - literal string segment (works on both targets).
    Utf8Lit(&'static str),
    /// `<<_:utf8>>` - wildcard utf8 segment
    Utf8Wild,
    /// `<<name:width>>` - binds an Int (width bits).
    Var(String, u8),
    /// `<<name:big-signed-8>>` - binds with endianness/signedness.
    VarInt(String, IntOpt),
    /// `<<_:big-signed-8>>` - discard with endianness/signedness.
    DiscardInt(IntOpt),
    /// `<<_:width>>` - fixed-width discard.
    Discard(u8),
    /// `<<_:bytes>>` - trailing bytes discard.
    Bytes,
}

#[derive(Debug, Clone, PartialEq)]
enum RestPat {
    Closed,
    Open,
    Named(String),
}

#[derive(Debug, Clone)]
pub enum Stmt {
    Let(String, Expr),
    Echo(Expr),
}

#[derive(Debug, Clone, Copy)]
pub enum Helper {
    /// `spin(n, acc)` - tail-recursive integer sum from 1 to n.
    Spin,
    /// `walk(xs, acc)` - tail-recursive list sum.
    Walk,
}

/// Concrete body for each helper. `to_source` renders these literally so
/// they cannot be generated by the generic expression machinery.
const fn helper_body(helper: Helper) -> &'static str {
    match helper {
        Helper::Spin => {
            "fn spin(n: Int, acc: Int) -> Int {\n  case n <= 0 {\n    True -> acc\n    False -> spin(n - 1, acc + n)\n  }\n}\n\n"
        }
        Helper::Walk => {
            "fn walk(xs: List(Int), acc: Int) -> Int {\n  case xs {\n    [] -> acc\n    [x, ..rest] -> walk(rest, acc + x)\n  }\n}\n\n"
        }
    }
}

fn helper_signature(helper: Helper) -> (&'static str, Vec<(&'static str, Ty)>, Ty) {
    match helper {
        Helper::Spin => ("spin", vec![("n", Ty::Int), ("acc", Ty::Int)], Ty::Int),
        Helper::Walk => ("walk", vec![("xs", Ty::ListInt), ("acc", Ty::Int)], Ty::Int),
    }
}

#[derive(Debug, Clone)]
pub struct Module {
    types: Vec<CustomType>,
    constants: Vec<(String, Ty, Expr)>,
    helper: Option<Helper>,
    functions: Vec<(FnSig, Expr)>,
    main: Vec<Stmt>,
}

impl Module {
    /// Get the statements from the main function.
    pub fn main_stmts(&self) -> &[Stmt] {
        &self.main
    }
}

const VAR_POOL: &[&str] = &[
    "x",
    "y",
    "z",
    "n",
    "m",
    "s",
    "l",
    "rest",
    "value",
    "acc",
    "item",
    "pair",
    "v",
    "constructor",
    "arguments",
    "prototype",
    "class",
    "new",
    "delete",
    "default",
    "length",
    "self_",
    "this_",
];
/// Function names that are reserved words in JavaScript but valid
/// identifiers in Gleam.
const JS_KEYWORDS: &[&str] = &[
    "delete",
    "new",
    "class",
    "default",
    "export",
    "extends",
    "static",
    "yield",
    "arguments",
    "constructor",
];
const TYPE_POOL: &[&str] = &["Number", "Record", "Promise", "Object", "Symbol", "Map"];
const CTOR_POOL: &[&str] = &["Ok", "Error", "Some", "None", "Number", "Record"];
const LABEL_POOL: &[&str] = &["value", "inner", "data", "constructor", "field"];
const STR_POOL: &[&str] = &[
    "",
    "a",
    "ab",
    "abc",
    "b",
    "bc",
    "x",
    "data",
    "res",
    "constructor",
];

const STR_1CHAR: &[&str] = &["a", "b", "x"];
const INT_POOL: &[i64] = &[0, 1, 2, 3, 4, 5, 7, 10, 42, 100];

#[expect(
    clippy::approx_constant,
    reason = "the generated Gleam must render the literal 3.14, not PI"
)]
const FLOAT_POOL: &[f64] = &[0.0, 1.0, 2.0, 0.5, 1.5, 3.14, 100.0, 0.1, 0.25, 10.0];

type Env = Vec<(String, Ty)>;

fn env_push(env: &mut Env, name: String, ty: Ty) {
    env.retain(|(n, _)| *n != name);
    env.push((name, ty));
}

struct Ctx {
    types: Vec<CustomType>,
    fns: Vec<FnSig>,
    counter: usize,
}

impl Ctx {
    fn fresh(&mut self) -> String {
        let n = format!("v{}", self.counter);
        self.counter += 1;
        n
    }

    /// Choose a name from the env to shadow.
    fn pick_shadow_name(&self, u: &mut Unstructured<'_>, env: &Env) -> Result<Option<String>> {
        let candidates: Vec<&String> = env.iter().map(|(n, _)| n).collect();
        if candidates.is_empty() {
            return Ok(None);
        }
        Ok(Some(pick(u, &candidates)?.to_string()))
    }
}

fn pick<'u, 's, T>(u: &mut Unstructured<'u>, xs: &'s [T]) -> Result<&'s T> {
    let i = u.int_in_range(0..=xs.len().saturating_sub(1))?;
    Ok(&xs[i])
}

fn chance(u: &mut Unstructured<'_>, pct: u8) -> Result<bool> {
    Ok(u.int_in_range(0..=99)? < pct)
}

fn roll(u: &mut Unstructured<'_>, weights: &[(u32, usize)]) -> Result<usize> {
    let total: u32 = weights.iter().map(|(w, _)| w).sum();
    let mut r = u.int_in_range(0..=total - 1)?;
    for (w, i) in weights {
        if r < *w {
            return Ok(*i);
        }
        r -= w;
    }
    Ok(weights.last().expect("nonempty weights").1)
}

#[derive(Clone)]
enum BindSpec {
    Free,
    One(String, Ty),
}

impl<'a> Arbitrary<'a> for Module {
    fn arbitrary(u: &mut Unstructured<'a>) -> Result<Self> {
        let mut ctx = Ctx {
            types: Vec::new(),
            fns: Vec::new(),
            counter: 0,
        };

        // custom types
        let type_count = roll(u, &[(25, 0), (35, 1), (25, 2), (15, 3)])?;
        let mut used_type_names: Vec<String> = Vec::new();
        let mut used_ctor_names: Vec<String> = Vec::new();
        for _ in 0..type_count {
            let name = loop {
                let cand = if chance(u, 60)? {
                    ctx.fresh().to_uppercase()
                } else {
                    pick(u, TYPE_POOL)?.to_string()
                };
                if !used_type_names.contains(&cand) {
                    used_type_names.push(cand.clone());
                    break cand;
                }
            };
            let ctor_count = u.int_in_range(1..=3)?;
            let mut ctors = Vec::new();
            for _ in 0..ctor_count {
                let cname = loop {
                    let cand = if chance(u, 60)? {
                        format!("C{}", ctx.fresh())
                    } else {
                        pick(u, CTOR_POOL)?.to_string()
                    };
                    if !used_ctor_names.contains(&cand) {
                        used_ctor_names.push(cand.clone());
                        break cand;
                    }
                };
                let field_count = u.int_in_range(0..=2)?;
                let mut fields = Vec::new();
                let mut label_seen = false;
                let mut used_labels: Vec<String> = Vec::new();
                for _ in 0..field_count {
                    let fty = gen_simple_ty(u, &ctx.types)?;
                    // Unlabelled fields must precede labelled ones.
                    let label = if label_seen || chance(u, 40)? {
                        label_seen = true;
                        // Labels must be unique within a constructor.
                        let candidates: Vec<&str> = LABEL_POOL
                            .iter()
                            .filter(|l| !used_labels.contains(&l.to_string()))
                            .copied()
                            .collect();
                        match candidates.first() {
                            Some(l) => {
                                used_labels.push(l.to_string());
                                Some(l.to_string())
                            }
                            None => Some(format!("label{}", ctx.fresh())),
                        }
                    } else {
                        None
                    };
                    fields.push((label, fty));
                }
                ctors.push(Ctor {
                    name: cname,
                    fields,
                });
            }
            ctx.types.push(CustomType { name, ctors });
        }

        // recursion helper: an `fn spin` or `fn walk` that other functions
        // can call, exercising tail-call handling.
        let helper: Option<Helper> = if chance(u, 50)? {
            let helper = *pick(u, &[Helper::Spin, Helper::Walk])?;
            let (name, params, ret) = helper_signature(helper);
            ctx.fns.push(FnSig {
                name: name.to_string(),
                params: params
                    .into_iter()
                    .map(|(n, t)| (n.to_string(), t))
                    .collect(),
                ret,
            });
            Some(helper)
        } else {
            None
        };

        // functions
        let fn_count = u.int_in_range(1..=3)?;
        let mut functions: Vec<(FnSig, Expr)> = Vec::new();
        let mut used_fn_names: Vec<String> = ctx.fns.iter().map(|f| f.name.clone()).collect();
        for i in 0..fn_count {
            let mut name = if chance(u, 30)? {
                pick(u, JS_KEYWORDS)?.to_string()
            } else {
                format!("f{i}")
            };
            if used_fn_names.contains(&name) {
                name = format!("f{i}");
            }
            used_fn_names.push(name.clone());
            let param_count = u.int_in_range(1..=3)?;
            let mut params: Vec<(String, Ty)> = Vec::new();
            for _ in 0..param_count {
                let mut pname = if chance(u, 50)? {
                    pick(u, VAR_POOL)?.to_string()
                } else {
                    ctx.fresh()
                };
                // Argument names must be unique within a function.
                if params.iter().any(|(n, _)| *n == pname) {
                    pname = ctx.fresh();
                }
                let pty = gen_any_ty(u, &ctx.types)?;
                params.push((pname, pty));
            }
            let ret = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool, Ty::ListInt])?.clone();
            let sig = FnSig {
                name: name.clone(),
                params: params.clone(),
                ret: ret.clone(),
            };
            let body = gen_expr(u, &mut ctx, &params, &ret, 3)?;
            ctx.fns.push(sig.clone());
            functions.push((sig, body));
        }

        // constants
        let const_count = u.int_in_range(0..=3)?;
        let mut constants: Vec<(String, Ty, Expr)> = Vec::new();
        let mut used_const_names: Vec<String> = Vec::new();
        for _ in 0..const_count {
            let cty = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool])?.clone();
            let cname = loop {
                let cand = pick(
                    u,
                    &[
                        "limit_value",
                        "seed_value",
                        "tag_value",
                        "pi_value",
                        "euler_value",
                        "golden_value",
                    ],
                )?
                .to_string();
                if !used_const_names.contains(&cand) {
                    used_const_names.push(cand.clone());
                    break cand;
                }
            };
            let cval = gen_base(u, &mut ctx, &cty)?;
            constants.push((cname, cty, cval));
        }

        // main
        let mut main: Vec<Stmt> = Vec::new();
        let mut env: Env = Vec::new();
        for (name, ty, _) in &constants {
            env.push((name.clone(), ty.clone()));
        }
        let let_count = u.int_in_range(0..=2)?;
        for _ in 0..let_count {
            let ty = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool, Ty::ListInt])?.clone();
            let expr = gen_expr(u, &mut ctx, &env, &ty, 2)?;
            // Shadowing - sometimes reuse a name already bound in main.
            let name = if chance(u, 30)? {
                match ctx.pick_shadow_name(u, &env)? {
                    Some(n) => n,
                    None => pick(u, VAR_POOL)?.to_string(),
                }
            } else {
                pick(u, VAR_POOL)?.to_string()
            };
            env_push(&mut env, name.clone(), ty.clone());
            main.push(Stmt::Let(name, expr));
        }
        let echo_count = u.int_in_range(1..=4)?;
        for _ in 0..echo_count {
            let ty = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool, Ty::ListInt])?.clone();
            let expr = gen_expr(u, &mut ctx, &env, &ty, 3)?;
            main.push(Stmt::Echo(expr));
        }

        Ok(Module {
            types: ctx.types.clone(),
            constants,
            helper,
            functions,
            main,
        })
    }
}

fn gen_simple_ty(u: &mut Unstructured<'_>, _types: &[CustomType]) -> Result<Ty> {
    Ok(pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool, Ty::ListInt])?.clone())
}

fn gen_any_ty(u: &mut Unstructured<'_>, types: &[CustomType]) -> Result<Ty> {
    let mut weights: Vec<(u32, usize)> = vec![(25, 0), (10, 1), (15, 2), (20, 3), (12, 4), (10, 7)];
    if !types.is_empty() {
        weights.push((15, 5));
    }
    Ok(match roll(u, &weights)? {
        0 => Ty::Int,
        1 => Ty::Float,
        2 => Ty::Str,
        3 => Ty::Bool,
        4 => Ty::ListInt,
        7 => Ty::Tup(
            Box::new(gen_simple_ty(u, types)?),
            Box::new(gen_simple_ty(u, types)?),
        ),
        _ => Ty::Custom(u.int_in_range(0..=types.len() - 1)?),
    })
}

fn gen_expr(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    env: &Env,
    ty: &Ty,
    depth: u8,
) -> Result<Expr> {
    if matches!(ty, Ty::BitArray) {
        return gen_base(u, ctx, ty);
    }
    // Find variables in scope of the required type.
    let vars_of_ty: Vec<&String> = env
        .iter()
        .filter(|(_, t)| *t == *ty)
        .map(|(n, _)| n)
        .collect();
    if depth == 0 {
        if !vars_of_ty.is_empty() && chance(u, 50)? {
            return Ok(Expr::Var(pick(u, &vars_of_ty)?.to_string()));
        }
        return gen_base(u, ctx, ty);
    }

    let can_call = ctx.fns.iter().any(|f| f.ret == *ty);
    let can_pipe = can_call && matches!(ty, Ty::Int | Ty::Float | Ty::Str | Ty::Bool | Ty::ListInt);
    let mut weights: Vec<(u32, usize)> = vec![(30, 0)]; // base
    if matches!(ty, Ty::Int | Ty::Float | Ty::Str | Ty::Bool) {
        weights.push((20, 1)); // binop
    }
    if depth >= 2 {
        weights.push((25, 2)); // case
    }
    weights.push((8, 3)); // block
    if can_call {
        weights.push((10, 4));
    }
    if can_pipe {
        weights.push((5, 5));
    }
    weights.push((7, 6)); // anon fn application

    match roll(u, &weights)? {
        0 => {
            if !vars_of_ty.is_empty() && chance(u, 40)? {
                Ok(Expr::Var(pick(u, &vars_of_ty)?.to_string()))
            } else {
                gen_base(u, ctx, ty)
            }
        }
        1 => gen_binop(u, ctx, env, ty, depth),
        2 => gen_case_expr(u, ctx, env, ty, depth),
        3 => {
            let stmt_count = u.int_in_range(1..=2)?;
            let mut block_env = env.clone();
            let mut stmts: Vec<(String, Expr)> = Vec::new();
            for _ in 0..stmt_count {
                let lty = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool, Ty::ListInt])?.clone();
                let bound = gen_expr(u, ctx, &block_env, &lty, depth - 1)?;
                // Shadowing - reuse an in-scope name sometimes.
                let name = if chance(u, 25)? {
                    match ctx.pick_shadow_name(u, &block_env)? {
                        Some(n) => n,
                        None => pick(u, VAR_POOL)?.to_string(),
                    }
                } else {
                    pick(u, VAR_POOL)?.to_string()
                };
                env_push(&mut block_env, name.clone(), lty);
                stmts.push((name, bound));
            }
            let last = gen_expr(u, ctx, &block_env, ty, depth - 1)?;
            Ok(Expr::Block(stmts, Box::new(last)))
        }
        4 => gen_call(u, ctx, env, ty, depth),
        5 => {
            // pipe: <expr of param0 type> |> fname(<other args>)
            let sig: FnSig = {
                let candidates: Vec<&FnSig> = ctx
                    .fns
                    .iter()
                    .filter(|f| {
                        f.ret == *ty
                            && !f.params.is_empty()
                            && !env.iter().any(|(n, _)| *n == f.name)
                    })
                    .collect();
                if candidates.is_empty() {
                    return gen_call(u, ctx, env, ty, depth);
                }
                (*pick(u, &candidates)?).clone()
            };
            let first_ty = sig.params[0].1.clone();
            let first = gen_expr(u, ctx, env, &first_ty, depth - 1)?;
            let mut args = Vec::new();
            for (_, aty) in sig.params.iter().skip(1) {
                args.push(gen_expr(u, ctx, env, aty, 1)?);
            }
            Ok(Expr::Pipe {
                first: Box::new(first),
                name: sig.name.clone(),
                args,
            })
        }
        _ => {
            // anonymous function applied immediately
            let param_count = u.int_in_range(1..=2)?;
            let mut anon_env = env.clone();
            let mut params: Vec<String> = Vec::new();
            let mut args: Vec<Expr> = Vec::new();
            for _ in 0..param_count {
                let pty = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool])?.clone();
                let pname = ctx.fresh();
                env_push(&mut anon_env, pname.clone(), pty.clone());
                params.push(pname);
                args.push(gen_base(u, ctx, &pty)?);
            }
            let body = gen_expr(u, ctx, &anon_env, ty, depth - 1)?;
            Ok(Expr::ApplyAnon {
                params,
                body: Box::new(body),
                args,
            })
        }
    }
}

fn gen_base(u: &mut Unstructured<'_>, ctx: &mut Ctx, ty: &Ty) -> Result<Expr> {
    Ok(match ty {
        Ty::Int => Expr::IntLit(*pick(u, INT_POOL)?),
        Ty::Float => Expr::FloatLit(*pick(u, FLOAT_POOL)?),
        Ty::Str => Expr::StrLit(pick(u, STR_POOL)?),
        Ty::Bool => Expr::BoolLit(chance(u, 50)?),
        Ty::BitArray => gen_bit_array(u)?,
        Ty::ListInt => {
            let n = u.int_in_range(0..=2)?;
            let mut elems = Vec::new();
            for _ in 0..n {
                elems.push(Expr::IntLit(*pick(u, INT_POOL)?));
            }
            Expr::ListLit(elems)
        }
        Ty::Tup(a, b) => Expr::TupLit(
            Box::new(gen_base(u, ctx, a)?),
            Box::new(gen_base(u, ctx, b)?),
        ),
        Ty::Custom(k) => {
            let ctor = pick(u, &ctx.types[*k].ctors)?.clone();
            let mut args = Vec::new();
            for (_, fty) in &ctor.fields {
                args.push(gen_base(u, ctx, fty)?);
            }
            Expr::Call {
                name: ctor.name.clone(),
                args,
            }
        }
    })
}

const SEG_WIDTHS: &[u8] = &[8, 8, 8, 16, 16, 4, 1];

fn gen_bit_array(u: &mut Unstructured<'_>) -> Result<Expr> {
    let n = match roll(u, &[(40, 1), (30, 2), (30, 3)])? {
        1 => 1,
        2 => 2,
        _ => 3,
    };
    let mut segs = Vec::new();
    for _ in 0..n {
        let seg = if chance(u, 55)? {
            let s = if n == 1 {
                *pick(u, STR_1CHAR)?
            } else {
                *pick(u, STR_POOL)?
            };
            BitSeg::Utf8(s)
        } else {
            let val = *pick(u, INT_POOL)? as u32;
            let width = *pick(u, SEG_WIDTHS)?;
            BitSeg::Int(val, width)
        };
        segs.push(seg);
    }
    Ok(Expr::BitsLit(segs))
}

fn gen_var_int_seg(
    u: &mut Unstructured<'_>,
    bound: &mut Vec<(String, Ty)>,
    bound_one: &mut bool,
) -> Result<BitSegPat> {
    *bound_one = true;
    let name = pick(u, VAR_POOL)?.to_string();
    let opt = IntOpt {
        width: *pick(u, SEG_WIDTHS)?,
        big: chance(u, 50)?,
        signed: chance(u, 30)?,
    };
    if !bound.iter().any(|(n, _)| *n == name) {
        bound.push((name.clone(), Ty::Int));
        Ok(BitSegPat::VarInt(name, opt))
    } else {
        Ok(BitSegPat::DiscardInt(opt))
    }
}

fn gen_bit_pattern(
    u: &mut Unstructured<'_>,
    bound: &mut Vec<(String, Ty)>,
    is_last: bool,
) -> Result<Pattern> {
    if is_last && chance(u, 70)? {
        return Ok(Pattern::Discard);
    }
    let n = match roll(u, &[(45, 1), (35, 2), (20, 3)])? {
        1 => 1,
        2 => 2,
        _ => 3,
    };
    let mut segs: Vec<BitSegPat> = Vec::new();
    let mut bound_one = false;
    for i in 0..n {
        let is_last_seg = i == n - 1;

        let bytes_ok = is_last_seg;

        let seg = if n == 1 {
            match roll(u, &[(30, 0), (25, 1), (35, 2), (10, 4)])? {
                0 => BitSegPat::IntLit(*pick(u, INT_POOL)? as u32, *pick(u, SEG_WIDTHS)?),
                1 => BitSegPat::Utf8Lit(pick(u, STR_POOL)?),
                2 => BitSegPat::Utf8Wild,
                _ => BitSegPat::Discard(*pick(u, SEG_WIDTHS)?),
            }
        } else {
            match roll(
                u,
                &[
                    (22, 0),
                    (18, 1),
                    (18, 2),
                    (12, 3),
                    (12, 4),
                    (3, 5),
                    (5, 6),
                    (5, 7),
                    (5, 8),
                ],
            )? {
                0 => BitSegPat::IntLit(*pick(u, INT_POOL)? as u32, *pick(u, SEG_WIDTHS)?),
                1 => BitSegPat::Utf8Lit(pick(u, STR_POOL)?),
                2 => BitSegPat::Utf8Wild,
                3 if !bound_one => {
                    bound_one = true;
                    let name = pick(u, VAR_POOL)?.to_string();
                    let width = *pick(u, SEG_WIDTHS)?;
                    if !bound.iter().any(|(n, _)| *n == name) {
                        bound.push((name.clone(), Ty::Int));
                        BitSegPat::Var(name, width)
                    } else {
                        BitSegPat::Discard(width)
                    }
                }
                4 => BitSegPat::Discard(*pick(u, SEG_WIDTHS)?),
                5 if bytes_ok => BitSegPat::Bytes,

                6 if !bound_one => gen_var_int_seg(u, bound, &mut bound_one)?,
                _ => BitSegPat::DiscardInt(IntOpt {
                    width: *pick(u, SEG_WIDTHS)?,
                    big: chance(u, 50)?,
                    signed: chance(u, 30)?,
                }),
            }
        };
        segs.push(seg);
    }
    Ok(Pattern::Bits(segs))
}

#[expect(
    clippy::approx_constant,
    reason = "The float divisor pool includes 3.14 as a literal so the generated Gleam code prints 3.14 rather than a PI approximation."
)]
fn gen_binop(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    env: &Env,
    ty: &Ty,
    depth: u8,
) -> Result<Expr> {
    Ok(match ty {
        Ty::Int => match roll(u, &[(30, 0), (30, 1), (20, 2), (15, 3), (5, 4)])? {
            0 => Expr::Bin(
                BinOp::Add,
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
            ),
            1 => Expr::Bin(
                BinOp::Sub,
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
            ),
            2 => Expr::Bin(
                BinOp::Mul,
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
            ),
            3 => Expr::Bin(
                BinOp::Rem,
                Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
                Box::new(Expr::IntLit(u.int_in_range(1..=7)?)),
            ),
            _ => Expr::NegInt(Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?)),
        },
        Ty::Str => Expr::Bin(
            BinOp::Concat,
            Box::new(gen_expr(u, ctx, env, &Ty::Str, depth - 1)?),
            Box::new(gen_expr(u, ctx, env, &Ty::Str, depth - 1)?),
        ),
        Ty::Bool => match roll(u, &[(25, 0), (15, 1), (20, 2), (10, 3), (15, 4), (15, 5)])? {
            0 => {
                // comparison of ints
                let op = *pick(
                    u,
                    &[
                        BinOp::Eq,
                        BinOp::Ne,
                        BinOp::Lt,
                        BinOp::Le,
                        BinOp::Gt,
                        BinOp::Ge,
                    ],
                )?;
                Expr::Bin(
                    op,
                    Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
                    Box::new(gen_expr(u, ctx, env, &Ty::Int, depth - 1)?),
                )
            }
            1 => {
                let op = *pick(u, &[BinOp::Eq, BinOp::Ne])?;
                Expr::Bin(
                    op,
                    Box::new(gen_expr(u, ctx, env, &Ty::Str, depth - 1)?),
                    Box::new(gen_expr(u, ctx, env, &Ty::Str, depth - 1)?),
                )
            }
            2 => {
                let op = *pick(u, &[BinOp::And, BinOp::Or])?;
                Expr::Bin(
                    op,
                    Box::new(gen_expr(u, ctx, env, &Ty::Bool, depth - 1)?),
                    Box::new(gen_expr(u, ctx, env, &Ty::Bool, depth - 1)?),
                )
            }
            3 => Expr::NegBool(Box::new(gen_expr(u, ctx, env, &Ty::Bool, depth - 1)?)),
            4 => {
                let op = *pick(u, &[BinOp::FGt, BinOp::FGe, BinOp::FLt, BinOp::FLe])?;
                Expr::Bin(
                    op,
                    Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                    Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                )
            }
            _ => {
                let op = *pick(u, &[BinOp::Eq, BinOp::Ne])?;
                Expr::Bin(
                    op,
                    Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                    Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                )
            }
        },
        Ty::Float => match roll(u, &[(30, 0), (30, 1), (24, 2), (16, 3)])? {
            0 => Expr::Bin(
                BinOp::FAdd,
                Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
            ),
            1 => Expr::Bin(
                BinOp::FSub,
                Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
            ),
            2 => Expr::Bin(
                BinOp::FMul,
                Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
            ),
            _ => {
                let divisor = Expr::FloatLit(*pick(u, &[1.0, 0.5, 2.0, 10.0, 3.14][..])?);
                Expr::Bin(
                    BinOp::FDiv,
                    Box::new(gen_expr(u, ctx, env, &Ty::Float, depth - 1)?),
                    Box::new(divisor),
                )
            }
        },
        _ => gen_base(u, ctx, ty)?,
    })
}

fn gen_call(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    env: &Env,
    ty: &Ty,
    depth: u8,
) -> Result<Expr> {
    let candidates: Vec<FnSig> = ctx
        .fns
        .iter()
        .filter(|f| f.ret == *ty && !env.iter().any(|(n, _)| *n == f.name))
        .cloned()
        .collect();
    if candidates.is_empty() {
        return gen_base(u, ctx, ty);
    }
    let sig = pick(u, &candidates)?.clone();
    let mut args = Vec::new();
    for (_, aty) in &sig.params {
        args.push(gen_expr(u, ctx, env, aty, depth.saturating_sub(1))?.clone());
    }
    Ok(Expr::Call {
        name: sig.name,
        args,
    })
}

fn gen_case_expr(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    env: &Env,
    ret: &Ty,
    depth: u8,
) -> Result<Expr> {
    let subj_count = if chance(u, 30)? { 2 } else { 1 };
    let mut subj_tys: Vec<Ty> = Vec::new();
    let mut subjs: Vec<Expr> = Vec::new();
    for _ in 0..subj_count {
        let sty = gen_case_subject_ty(u, &ctx.types)?;
        subjs.push(gen_expr(u, ctx, env, &sty, 1)?);
        subj_tys.push(sty);
    }

    let clause_count = u.int_in_range(2..=3)?;
    let mut clauses: Vec<Clause> = Vec::new();
    let mut used_int_lits: Vec<u32> = Vec::new();
    let mut used_str_lits: Vec<&'static str> = Vec::new();
    let mut used_ctors: Vec<String> = Vec::new();

    for i in 0..clause_count {
        let is_last = i == clause_count - 1;

        let alts_allowed = subj_count == 1
            && !matches!(subj_tys[0], Ty::ListInt)
            && !matches!(subj_tys[0], Ty::BitArray);
        let with_alts = alts_allowed && chance(u, 25)?;
        let bind_spec = if alts_allowed && chance(u, 30)? {
            let name = pick(u, &["a", "b", "inner", "item", "constructor"][..])?.to_string();
            let bty = pick(u, &[Ty::Int, Ty::Float, Ty::Str, Ty::Bool])?.clone();
            BindSpec::One(name, bty)
        } else {
            BindSpec::Free
        };

        let mut pats: Vec<Pattern> = Vec::new();
        let mut bound: Vec<(String, Ty)> = Vec::new();
        for sty in &subj_tys {
            let pat = gen_pattern(
                u,
                ctx,
                env,
                &mut bound,
                &bind_spec,
                sty,
                &mut used_int_lits,
                &mut used_str_lits,
                &mut used_ctors,
                is_last,
                !with_alts,
            )?;
            pats.push(pat);
        }

        let mut alts: Vec<Pattern> = Vec::new();
        if with_alts {
            let subj0_binds = &bound[..];
            let alt = match (&subj_tys[0], subj0_binds) {
                (_, []) => Some(gen_alt_pattern(
                    u,
                    ctx,
                    &BindSpec::Free,
                    &subj_tys[0],
                    &mut used_int_lits,
                    &mut used_str_lits,
                )?),
                (Ty::ListInt | Ty::Str, [(n, t)]) => Some(gen_alt_pattern(
                    u,
                    ctx,
                    &BindSpec::One(n.clone(), t.clone()),
                    &subj_tys[0],
                    &mut used_int_lits,
                    &mut used_str_lits,
                )?),
                _ => None,
            };
            if let Some(alt) = alt {
                alts.push(alt);
            }
        }

        let all_catchall = pats
            .iter()
            .all(|p| matches!(p, Pattern::Discard | Pattern::Var(_)));
        let has_guard_eligible_binds = bound
            .iter()
            .any(|(_, t)| matches!(t, Ty::Int | Ty::Str | Ty::Bool));

        let guard = if !is_last
            && !all_catchall
            && has_guard_eligible_binds
            && alts.is_empty()
            && chance(u, 40)?
        {
            Some(gen_guard(u, &bound)?)
        } else {
            None
        };

        let mut body_env = env.clone();
        for (n, t) in &bound {
            env_push(&mut body_env, n.clone(), t.clone());
        }
        let body = gen_expr(u, ctx, &body_env, ret, depth - 1)?;
        clauses.push(Clause {
            pats,
            alts,
            guard,
            body,
        });
    }

    if !covers(ctx, &subj_tys, &clauses) {
        let pats: Vec<Pattern> = subj_tys
            .iter()
            .map(|_| {
                if chance(u, 50).unwrap_or(false) {
                    Pattern::Discard
                } else {
                    Pattern::Var(ctx.fresh())
                }
            })
            .collect();
        let mut body_env = env.clone();
        for (i, p) in pats.iter().enumerate() {
            if let Pattern::Var(name) = p {
                env_push(&mut body_env, name.clone(), subj_tys[i].clone());
            }
        }
        let body = gen_expr(u, ctx, &body_env, ret, depth - 1)?;
        clauses.push(Clause {
            pats,
            alts: Vec::new(),
            guard: None,
            body,
        });
    }

    Ok(Expr::Case { subjs, clauses })
}

fn covers(ctx: &Ctx, subj_tys: &[Ty], clauses: &[Clause]) -> bool {
    for c in clauses {
        let catchall = c.pats.iter().all(|p| match p {
            Pattern::Discard | Pattern::Var(_) => true,
            Pattern::Alias(inner, _) => matches!(**inner, Pattern::Discard | Pattern::Var(_)),
            _ => false,
        });
        if catchall && c.guard.is_none() {
            return true;
        }
    }
    if let [Ty::Bool] = subj_tys {
        let mut seen = (false, false);
        for c in clauses {
            if c.guard.is_some() {
                continue;
            }
            for p in &c.pats {
                match p {
                    Pattern::BoolLit(true) => seen.0 = true,
                    Pattern::BoolLit(false) => seen.1 = true,
                    _ => {}
                }
            }
        }
        if seen.0 && seen.1 {
            return true;
        }
    }
    if let [Ty::Custom(k)] = subj_tys {
        let all: Vec<&str> = ctx.types[*k]
            .ctors
            .iter()
            .map(|c| c.name.as_str())
            .collect();
        let used: Vec<&str> = clauses
            .iter()
            .filter(|c| c.guard.is_none())
            .filter_map(|c| match &c.pats[0] {
                Pattern::CtorPat { name, fields }
                    if fields
                        .iter()
                        .all(|f| matches!(f, Pattern::Discard | Pattern::Var(_))) =>
                {
                    Some(name.as_str())
                }
                _ => None,
            })
            .collect();
        if all.iter().all(|n| used.contains(n)) {
            return true;
        }
    }
    false
}

fn gen_case_subject_ty(u: &mut Unstructured<'_>, types: &[CustomType]) -> Result<Ty> {
    let mut weights: Vec<(u32, usize)> =
        vec![(20, 0), (25, 1), (10, 2), (12, 3), (5, 4), (8, 6), (10, 7)];
    if !types.is_empty() {
        weights.push((20, 5));
    }
    Ok(match roll(u, &weights)? {
        0 => Ty::Int,
        1 => Ty::Str,
        2 => Ty::Bool,
        3 => Ty::ListInt,
        4 => Ty::Tup(
            Box::new(gen_simple_ty(u, types)?),
            Box::new(gen_simple_ty(u, types)?),
        ),
        6 => Ty::BitArray,
        7 => Ty::Float,
        _ => Ty::Custom(u.int_in_range(0..=types.len() - 1)?),
    })
}

#[expect(
    clippy::too_many_arguments,
    reason = "Pattern construction combines the generation state with the name-uniqueness pools for each clause."
)]
fn gen_pattern(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    env: &Env,
    bound: &mut Vec<(String, Ty)>,
    spec: &BindSpec,
    ty: &Ty,
    used_ints: &mut Vec<u32>,
    used_strs: &mut Vec<&'static str>,
    used_ctors: &mut Vec<String>,
    is_last: bool,
    allow_alias: bool,
) -> Result<Pattern> {
    if let BindSpec::One(name, bty) = spec {
        return gen_one_pattern(u, ctx, bound, name, bty, ty);
    }

    let binder = |u: &mut Unstructured<'_>,
                  bound: &mut Vec<(String, Ty)>,
                  ctx: &mut Ctx,
                  ty: &Ty|
     -> Result<Pattern> {
        // Shadowing - sometimes reuse a name from the outer env.
        let name = if chance(u, 20)? {
            match ctx.pick_shadow_name(u, env)? {
                Some(n) => n,
                None => pick(u, VAR_POOL)?.to_string(),
            }
        } else if chance(u, 40)? {
            pick(u, VAR_POOL)?.to_string()
        } else {
            ctx.fresh()
        };
        // Never bind the same name twice in one clause.
        if bound.iter().any(|(n, _)| *n == name) {
            return Ok(Pattern::Discard);
        }
        bound.push((name.clone(), ty.clone()));
        Ok(Pattern::Var(name))
    };

    let mut pat = match ty {
        Ty::Int => match roll(u, &[(50, 0), (20, 1), (30, 2)])? {
            0 => {
                let lit = fresh_int_lit(u, used_ints)?;
                used_ints.push(lit);
                Pattern::IntLit(lit)
            }
            1 => binder(u, bound, ctx, ty)?,
            _ => Pattern::Discard,
        },
        Ty::Float => match roll(u, &[(50, 0), (20, 1), (30, 2)])? {
            0 => Pattern::FloatLit(*pick(u, FLOAT_POOL)?),
            1 => binder(u, bound, ctx, ty)?,
            _ => Pattern::Discard,
        },
        Ty::Str => match roll(u, &[(35, 0), (25, 1), (15, 2), (25, 3)])? {
            0 => {
                let lit = fresh_str_lit(u, used_strs)?;
                used_strs.push(lit);
                Pattern::StrLit(lit)
            }
            1 => {
                let prefix = *pick(u, STR_POOL)?;
                let rest = if chance(u, 60)? {
                    let candidates: Vec<&str> = ["rest", "tail", "suffix", "s"]
                        .into_iter()
                        .filter(|n| !bound.iter().any(|(b, _)| b == n))
                        .collect();
                    match candidates.first() {
                        Some(name) => {
                            bound.push((name.to_string(), Ty::Str));
                            Some(name.to_string())
                        }
                        None => None,
                    }
                } else {
                    None
                };
                Pattern::Prefix(prefix, rest)
            }
            2 => binder(u, bound, ctx, ty)?,
            _ => Pattern::Discard,
        },
        Ty::Bool => match roll(u, &[(50, 0), (20, 1), (30, 2)])? {
            0 => Pattern::BoolLit(chance(u, 50)?),
            1 => binder(u, bound, ctx, ty)?,
            _ => Pattern::Discard,
        },
        Ty::ListInt => gen_list_pattern(u, ctx, env, bound, ty)?,
        Ty::Tup(a, b) => Pattern::TupPat(
            Box::new(gen_pattern(
                u,
                ctx,
                env,
                bound,
                &BindSpec::Free,
                a,
                used_ints,
                used_strs,
                used_ctors,
                is_last,
                true,
            )?),
            Box::new(gen_pattern(
                u,
                ctx,
                env,
                bound,
                &BindSpec::Free,
                b,
                used_ints,
                used_strs,
                used_ctors,
                is_last,
                true,
            )?),
        ),
        Ty::Custom(k) => match roll(u, &[(60, 0), (15, 1), (25, 2)])? {
            0 => {
                let ctor = pick(u, &ctx.types[*k].ctors)?.clone();
                let mut fields = Vec::new();
                for (_, fty) in &ctor.fields {
                    fields.push(gen_pattern(
                        u,
                        ctx,
                        env,
                        bound,
                        &BindSpec::Free,
                        fty,
                        used_ints,
                        used_strs,
                        used_ctors,
                        is_last,
                        true,
                    )?);
                }
                used_ctors.push(ctor.name.clone());
                Pattern::CtorPat {
                    name: ctor.name.clone(),
                    fields,
                }
            }
            1 => binder(u, bound, ctx, ty)?,
            _ => Pattern::Discard,
        },
        Ty::BitArray => gen_bit_pattern(u, bound, is_last)?,
    };

    // Alias patterns (whole-pattern binding) — only when the pattern isn't
    // already a bare variable and only when not last-position generated
    // alternatives are in play (alternatives handled by caller).
    if allow_alias && !matches!(pat, Pattern::Var(_) | Pattern::Discard) && chance(u, 12)? {
        let candidates: Vec<&str> = ["whole", "it", "subject_"]
            .into_iter()
            .filter(|n| !bound.iter().any(|(b, _)| b == n))
            .collect();
        if let Some(name) = candidates.first() {
            bound.push((name.to_string(), ty.clone()));
            pat = Pattern::Alias(Box::new(pat), name.to_string());
        }
    }
    Ok(pat)
}

fn gen_one_pattern(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    bound: &mut Vec<(String, Ty)>,
    name: &str,
    bty: &Ty,
    ty: &Ty,
) -> Result<Pattern> {
    let pat = match (ty, bty) {
        (Ty::Str, Ty::Str) => {
            let prefix = pick(u, STR_POOL)?;
            bound.push((name.to_string(), Ty::Str));
            Pattern::Prefix(prefix, Some(name.to_string()))
        }
        (Ty::ListInt, Ty::Int) => {
            bound.push((name.to_string(), Ty::Int));
            if chance(u, 50)? {
                Pattern::ListCons {
                    elems: vec![Pattern::Var(name.to_string())],
                    rest: RestPat::Closed,
                }
            } else {
                Pattern::ListCons {
                    elems: vec![Pattern::Var(name.to_string()), Pattern::Discard],
                    rest: RestPat::Closed,
                }
            }
        }
        (Ty::Custom(k), _) => {
            let ctors = &ctx.types[*k].ctors;
            let compatible: Vec<&Ctor> = ctors
                .iter()
                .filter(|c| c.fields.iter().any(|(_, f)| f == bty))
                .collect();
            if compatible.is_empty() {
                bound.push((name.to_string(), ty.clone()));
                Pattern::Var(name.to_string())
            } else {
                let ctor = pick(u, &compatible)?;
                let fields: Vec<Pattern> = ctor
                    .fields
                    .iter()
                    .map(|(_, f)| {
                        if f == bty && !bound.iter().any(|(n, _)| n.as_str() == name) {
                            bound.push((name.to_string(), f.clone()));
                            Pattern::Var(name.to_string())
                        } else {
                            Pattern::Discard
                        }
                    })
                    .collect();
                Pattern::CtorPat {
                    name: ctor.name.clone(),
                    fields,
                }
            }
        }
        _ => {
            bound.push((name.to_string(), ty.clone()));
            Pattern::Var(name.to_string())
        }
    };
    Ok(pat)
}

fn gen_alt_pattern(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    spec: &BindSpec,
    ty: &Ty,
    used_ints: &mut Vec<u32>,
    used_strs: &mut Vec<&'static str>,
) -> Result<Pattern> {
    if let BindSpec::One(name, bty) = spec {
        return match (ty, bty) {
            (Ty::ListInt, Ty::Int) => Ok(Pattern::ListCons {
                elems: vec![Pattern::Var(name.clone())],
                rest: RestPat::Open,
            }),
            (Ty::Str, Ty::Str) => Ok(Pattern::Prefix(pick(u, STR_POOL)?, Some(name.clone()))),
            _ => Ok(Pattern::Var(name.clone())),
        };
    }
    Ok(match ty {
        Ty::Int => {
            let lit = fresh_int_lit(u, used_ints)?;
            used_ints.push(lit);
            Pattern::IntLit(lit)
        }
        Ty::Float => Pattern::FloatLit(*pick(u, FLOAT_POOL)?),
        Ty::Str => {
            if chance(u, 50)? {
                let lit = fresh_str_lit(u, used_strs)?;
                used_strs.push(lit);
                Pattern::StrLit(lit)
            } else {
                Pattern::Prefix(pick(u, STR_POOL)?, None)
            }
        }
        Ty::Bool => Pattern::BoolLit(chance(u, 50)?),
        Ty::ListInt => match roll(u, &[(40, 0), (30, 1), (30, 2)])? {
            0 => Pattern::ListNil,
            1 => Pattern::ListCons {
                elems: vec![Pattern::Discard],
                rest: RestPat::Closed,
            },
            _ => Pattern::ListCons {
                elems: vec![Pattern::Discard, Pattern::Discard],
                rest: RestPat::Open,
            },
        },
        Ty::Tup(a, b) => Pattern::TupPat(
            Box::new(gen_alt_pattern(u, ctx, spec, a, used_ints, used_strs)?),
            Box::new(gen_alt_pattern(u, ctx, spec, b, used_ints, used_strs)?),
        ),
        Ty::Custom(k) => {
            let ctor = pick(u, &ctx.types[*k].ctors)?;
            Pattern::CtorPat {
                name: ctor.name.clone(),
                fields: ctor.fields.iter().map(|_| Pattern::Discard).collect(),
            }
        }
        Ty::BitArray => Pattern::Discard,
    })
}

fn gen_list_pattern(
    u: &mut Unstructured<'_>,
    ctx: &mut Ctx,
    env: &Env,
    bound: &mut Vec<(String, Ty)>,
    _ty: &Ty,
) -> Result<Pattern> {
    let elem = |u: &mut Unstructured<'_>, bound: &mut Vec<(String, Ty)>, ctx: &mut Ctx| {
        Ok(match roll(u, &[(40, 0), (35, 1), (25, 2)])? {
            0 => Pattern::IntLit(u.int_in_range(0..=9)?),
            1 => {
                let name = if chance(u, 20)? {
                    match ctx.pick_shadow_name(u, env)? {
                        Some(n) => n,
                        None => pick(u, &["a", "b", "h", "x", "constructor"][..])?.to_string(),
                    }
                } else {
                    pick(u, &["a", "b", "h", "x", "constructor"][..])?.to_string()
                };
                if bound.iter().any(|(n, _)| *n == name) {
                    Pattern::Discard
                } else {
                    bound.push((name.clone(), Ty::Int));
                    Pattern::Var(name)
                }
            }
            _ => Pattern::Discard,
        })
    };
    Ok(match roll(u, &[(20, 0), (25, 1), (25, 2), (30, 3)])? {
        0 => Pattern::ListNil,
        1 => Pattern::ListCons {
            elems: vec![elem(u, bound, ctx)?],
            rest: RestPat::Closed,
        },
        2 => Pattern::ListCons {
            elems: vec![elem(u, bound, ctx)?, elem(u, bound, ctx)?],
            rest: RestPat::Open,
        },
        _ => {
            let candidates: Vec<&str> = ["rest", "tail", "tl"]
                .into_iter()
                .filter(|n| !bound.iter().any(|(b, _)| b == n))
                .collect();
            match candidates.first() {
                Some(rest_name) => {
                    bound.push((rest_name.to_string(), Ty::ListInt));
                    Pattern::ListCons {
                        elems: vec![elem(u, bound, ctx)?],
                        rest: RestPat::Named(rest_name.to_string()),
                    }
                }
                None => Pattern::ListCons {
                    elems: vec![elem(u, bound, ctx)?],
                    rest: RestPat::Open,
                },
            }
        }
    })
}

fn fresh_int_lit(u: &mut Unstructured<'_>, used: &[u32]) -> Result<u32> {
    let mut candidates: Vec<u32> = (0..=9).filter(|n| !used.contains(n)).collect();
    if candidates.is_empty() {
        candidates.push(10);
    }
    Ok(candidates[u.int_in_range(0..=candidates.len() - 1)?])
}

fn fresh_str_lit(u: &mut Unstructured<'_>, used: &[&'static str]) -> Result<&'static str> {
    let candidates: Vec<&'static str> = STR_POOL
        .iter()
        .filter(|s| !used.contains(*s) && !s.is_empty())
        .copied()
        .collect();
    if candidates.is_empty() {
        return Ok("zzz");
    }
    Ok(candidates[u.int_in_range(0..=candidates.len() - 1)?])
}

fn gen_guard(u: &mut Unstructured<'_>, bound: &[(String, Ty)]) -> Result<Expr> {
    let usable: Vec<&(String, Ty)> = bound
        .iter()
        .filter(|(_, t)| matches!(t, Ty::Int | Ty::Str | Ty::Bool | Ty::Float))
        .collect();
    let atom = |u: &mut Unstructured<'_>| -> Result<Expr> {
        let (name, ty) = pick(u, &usable)?;
        Ok(match ty {
            Ty::Int => {
                let lit = u.int_in_range(0..=9)?;
                match roll(u, &[(30, 0), (30, 1), (25, 2), (15, 3)])? {
                    0 => Expr::Bin(
                        BinOp::Gt,
                        Box::new(Expr::Var(name.clone())),
                        Box::new(Expr::IntLit(lit)),
                    ),
                    1 => Expr::Bin(
                        BinOp::Le,
                        Box::new(Expr::Var(name.clone())),
                        Box::new(Expr::IntLit(lit)),
                    ),
                    2 => Expr::Bin(
                        BinOp::Eq,
                        Box::new(Expr::Var(name.clone())),
                        Box::new(Expr::IntLit(lit)),
                    ),
                    _ => Expr::Bin(
                        BinOp::Eq,
                        Box::new(Expr::Bin(
                            BinOp::Rem,
                            Box::new(Expr::Var(name.clone())),
                            Box::new(Expr::IntLit(2)),
                        )),
                        Box::new(Expr::IntLit(0)),
                    ),
                }
            }
            Ty::Str => {
                let lit = *pick(u, STR_POOL)?;
                let op = *pick(u, &[BinOp::Eq, BinOp::Ne])?;
                Expr::Bin(
                    op,
                    Box::new(Expr::Var(name.clone())),
                    Box::new(Expr::StrLit(lit)),
                )
            }
            Ty::Float => {
                let lit = *pick(u, FLOAT_POOL)?;
                let op = *pick(u, &[BinOp::FGt, BinOp::FGe, BinOp::FLt, BinOp::FLe])?;
                Expr::Bin(
                    op,
                    Box::new(Expr::Var(name.clone())),
                    Box::new(Expr::FloatLit(lit)),
                )
            }
            _ => {
                if chance(u, 50)? {
                    Expr::Var(name.clone())
                } else {
                    Expr::NegBool(Box::new(Expr::Var(name.clone())))
                }
            }
        })
    };
    let left = atom(u)?;
    if chance(u, 35)? {
        let right = atom(u)?;
        let op = *pick(u, &[BinOp::And, BinOp::Or])?;
        Ok(Expr::Bin(op, Box::new(left), Box::new(right)))
    } else {
        Ok(left)
    }
}

impl Module {
    pub fn to_source(&self) -> String {
        let mut out = String::new();
        for (name, ty, val) in &self.constants {
            out.push_str("pub const ");
            out.push_str(name);
            out.push_str(": ");
            out.push_str(&ty_str(ty, &self.types));
            out.push_str(" = ");

            write_expr(&mut out, val, &self.types, 0);
            out.push('\n');
        }
        if !self.constants.is_empty() {
            out.push('\n');
        }
        for t in &self.types {
            out.push_str("pub type ");
            out.push_str(&t.name);
            out.push_str(" {\n");
            for c in &t.ctors {
                out.push_str("  ");
                out.push_str(&c.name);
                if !c.fields.is_empty() {
                    out.push('(');
                    let fields: Vec<String> = c
                        .fields
                        .iter()
                        .map(|(label, fty)| match label {
                            Some(l) => format!("{l}: {}", ty_str(fty, &self.types)),
                            None => ty_str(fty, &self.types),
                        })
                        .collect();
                    out.push_str(&fields.join(", "));
                    out.push(')');
                }
                out.push('\n');
            }
            out.push_str("}\n\n");
        }

        if let Some(helper) = self.helper {
            out.push_str(helper_body(helper));
        }

        for (sig, body) in &self.functions {
            out.push_str("fn ");
            out.push_str(&sig.name);
            out.push('(');
            let params: Vec<String> = sig
                .params
                .iter()
                .map(|(n, t)| format!("{n}: {}", ty_str(t, &self.types)))
                .collect();
            out.push_str(&params.join(", "));
            out.push_str(") -> ");
            out.push_str(&ty_str(&sig.ret, &self.types));
            out.push_str(" {\n");
            write_expr(&mut out, body, &self.types, 1);
            out.push_str("\n}\n\n");
        }

        out.push_str("pub fn main() {\n");
        for stmt in &self.main {
            out.push_str("  ");
            match stmt {
                Stmt::Let(name, expr) => {
                    out.push_str("let ");
                    out.push_str(name);
                    out.push_str(" = ");
                    write_expr(&mut out, expr, &self.types, 1);
                }
                Stmt::Echo(expr) => {
                    out.push_str("echo ");
                    write_expr(&mut out, expr, &self.types, 1);
                }
            }
            out.push('\n');
        }
        out.push_str("}\n");
        out
    }

    /// Deterministic generation from a u64 seed
    pub fn from_seed(seed: u64) -> Module {
        let mut state = seed ^ 0x9E37_79B9_7F4A_7C15;
        let mut bytes = vec![0u8; 2048];
        for _ in 0..8 {
            for chunk in bytes.chunks_mut(8) {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                let le = state.to_le_bytes();
                let n = chunk.len();
                chunk.copy_from_slice(&le[..n]);
            }
            let mut u = Unstructured::new(&bytes);
            if let Ok(m) = Module::arbitrary(&mut u) {
                return m;
            }
        }
        // Unreachable in practice
        Module {
            types: Vec::new(),
            constants: Vec::new(),
            helper: None,
            functions: vec![(
                FnSig {
                    name: "f0".to_string(),
                    params: vec![("x".to_string(), Ty::Int)],
                    ret: Ty::Int,
                },
                Expr::Var("x".to_string()),
            )],
            main: vec![Stmt::Echo(Expr::IntLit(0))],
        }
    }
}

fn ty_str(ty: &Ty, types: &[CustomType]) -> String {
    match ty {
        Ty::Int => "Int".to_string(),
        Ty::Float => "Float".to_string(),
        Ty::Str => "String".to_string(),
        Ty::Bool => "Bool".to_string(),
        Ty::ListInt => "List(Int)".to_string(),
        Ty::Tup(a, b) => format!("#({}, {})", ty_str(a, types), ty_str(b, types)),
        Ty::Custom(k) => types[*k].name.clone(),
        Ty::BitArray => "BitArray".to_string(),
    }
}

fn binop_str(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Rem => "%",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::Concat => "<>",
        BinOp::FAdd => "+.",
        BinOp::FSub => "-.",
        BinOp::FMul => "*.",
        BinOp::FDiv => "/.",
        BinOp::FGt => ">.",
        BinOp::FGe => ">=.",
        BinOp::FLt => "<.",
        BinOp::FLe => "<=.",
    }
}

fn atomic(e: &Expr) -> bool {
    matches!(
        e,
        Expr::IntLit(_)
            | Expr::StrLit(_)
            | Expr::BoolLit(_)
            | Expr::Var(_)
            | Expr::ListLit(_)
            | Expr::TupLit(..)
            | Expr::Call { .. }
    )
}

fn write_operand(out: &mut String, e: &Expr, types: &[CustomType], ind: usize) {
    if atomic(e) {
        return write_expr(out, e, types, ind);
    }
    out.push('{');
    push_indent(out, ind + 1);
    write_expr(out, e, types, ind + 1);
    push_indent(out, ind);
    out.push('}');
}

fn write_expr(out: &mut String, e: &Expr, types: &[CustomType], ind: usize) {
    match e {
        Expr::IntLit(n) => out.push_str(&n.to_string()),
        Expr::FloatLit(f) => {
            let s = format!("{}", f);
            if s.contains('.') || s.contains('e') {
                out.push_str(&s);
            } else {
                out.push_str(&format!("{}.0", s));
            }
        }
        Expr::StrLit(s) => {
            out.push('"');
            out.push_str(s);
            out.push('"');
        }
        Expr::BoolLit(b) => out.push_str(if *b { "True" } else { "False" }),
        Expr::Var(name) => out.push_str(name),
        Expr::ListLit(elems) => {
            out.push('[');
            for (i, el) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_expr(out, el, types, ind);
            }
            out.push(']');
        }
        Expr::TupLit(a, b) => {
            out.push_str("#(");
            write_expr(out, a, types, ind);
            out.push_str(", ");
            write_expr(out, b, types, ind);
            out.push(')');
        }
        Expr::Bin(op, l, r) => {
            write_operand(out, l, types, ind);
            out.push(' ');
            out.push_str(binop_str(*op));
            out.push(' ');
            write_operand(out, r, types, ind);
        }
        Expr::NegBool(x) => {
            out.push('!');
            write_operand(out, x, types, ind);
        }
        Expr::NegInt(x) => {
            out.push_str("0 - ");
            write_operand(out, x, types, ind);
        }
        Expr::Case { subjs, clauses } => {
            out.push_str("case ");
            for (i, s) in subjs.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_expr(out, s, types, ind + 1);
            }
            out.push_str(" {");
            for c in clauses {
                push_indent(out, ind + 1);
                write_clause(out, c, types, ind + 1);
            }
            push_indent(out, ind);
            out.push('}');
        }
        Expr::Block(stmts, last) => {
            out.push('{');
            for (name, bound) in stmts {
                push_indent(out, ind + 1);
                out.push_str("let ");
                out.push_str(name);
                out.push_str(" = ");
                write_expr(out, bound, types, ind + 1);
            }
            push_indent(out, ind + 1);
            write_expr(out, last, types, ind + 1);
            push_indent(out, ind);
            out.push('}');
        }
        Expr::Call { name, args } => {
            out.push_str(name);
            if !args.is_empty() {
                out.push('(');
                for (i, a) in args.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    write_expr(out, a, types, ind);
                }
                out.push(')');
            }
        }
        Expr::Pipe { first, name, args } => {
            write_operand(out, first, types, ind);
            out.push_str(" |> ");
            out.push_str(name);
            out.push('(');
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_expr(out, a, types, ind);
            }
            out.push(')');
        }
        Expr::ApplyAnon { params, body, args } => {
            out.push_str("fn(");
            out.push_str(&params.join(", "));
            out.push_str(") { ");
            write_expr(out, body, types, ind);
            out.push_str(" }(");
            for (i, a) in args.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_expr(out, a, types, ind);
            }
            out.push(')');
        }
        Expr::BitsLit(segs) => {
            out.push_str("<<");
            for (i, s) in segs.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                match s {
                    BitSeg::Int(val, width) => {
                        out.push_str(&val.to_string());
                        out.push(':');
                        out.push_str(&width.to_string());
                    }
                    BitSeg::Utf8(s) => {
                        out.push('"');
                        out.push_str(s);
                        out.push_str("\":utf8");
                    }
                }
            }
            out.push_str(">>");
        }
    }
}

fn write_clause(out: &mut String, c: &Clause, types: &[CustomType], ind: usize) {
    let last = c.pats.len() - 1;
    for (i, p) in c.pats.iter().enumerate() {
        write_pattern(out, p);
        if i != last {
            out.push_str(", ");
        }
    }
    for alt in &c.alts {
        out.push_str(" | ");
        write_pattern(out, alt);
    }
    if let Some(g) = &c.guard {
        out.push_str(" if ");
        write_guard(out, g, types, ind);
    }
    out.push_str(" -> ");
    write_expr(out, &c.body, types, ind);
}

fn write_pattern(out: &mut String, p: &Pattern) {
    match p {
        Pattern::Discard => out.push('_'),
        Pattern::Var(name) => out.push_str(name),
        Pattern::Alias(pat, name) => {
            write_pattern(out, pat);
            out.push_str(" as ");
            out.push_str(name);
        }
        Pattern::IntLit(n) => out.push_str(&n.to_string()),
        Pattern::FloatLit(f) => {
            let s = format!("{}", f);
            if s.contains('.') || s.contains('e') {
                out.push_str(&s);
            } else {
                out.push_str(&format!("{}.0", s));
            }
        }
        Pattern::StrLit(s) => {
            out.push('"');
            out.push_str(s);
            out.push('"');
        }
        Pattern::BoolLit(b) => out.push_str(if *b { "True" } else { "False" }),
        Pattern::Prefix(prefix, rest) => {
            out.push('"');
            out.push_str(prefix);
            out.push_str("\" <> ");
            match rest {
                Some(name) => out.push_str(name),
                None => out.push('_'),
            }
        }
        Pattern::ListNil => out.push_str("[]"),
        Pattern::ListCons { elems, rest } => {
            out.push('[');
            for (i, el) in elems.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                write_pattern(out, el);
            }
            match rest {
                RestPat::Closed => {}
                RestPat::Open => out.push_str(", .."),
                RestPat::Named(name) => {
                    out.push_str(", ..");
                    out.push_str(name);
                }
            }
            out.push(']');
        }
        Pattern::CtorPat { name, fields } => {
            out.push_str(name);
            if !fields.is_empty() {
                out.push('(');
                for (i, f) in fields.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    write_pattern(out, f);
                }
                out.push(')');
            }
        }
        Pattern::TupPat(a, b) => {
            out.push_str("#(");
            write_pattern(out, a);
            out.push_str(", ");
            write_pattern(out, b);
            out.push(')');
        }
        Pattern::Bits(segs) => {
            out.push_str("<<");
            for (i, s) in segs.iter().enumerate() {
                if i > 0 {
                    out.push_str(", ");
                }
                match s {
                    BitSegPat::IntLit(val, width) => {
                        out.push_str(&val.to_string());
                        out.push(':');
                        out.push_str(&width.to_string());
                    }
                    BitSegPat::Utf8Lit(s) => {
                        out.push('"');
                        out.push_str(s);
                        out.push_str("\":utf8");
                    }
                    BitSegPat::Utf8Wild => out.push_str("_:utf8"),
                    BitSegPat::Var(name, width) => {
                        out.push_str(name);
                        out.push(':');
                        out.push_str(&width.to_string());
                    }
                    BitSegPat::VarInt(name, opt) => {
                        out.push_str(name);
                        out.push(':');
                        out.push_str(&fmt_int_opt(opt));
                    }
                    BitSegPat::Discard(width) => {
                        out.push('_');
                        out.push(':');
                        out.push_str(&width.to_string());
                    }
                    BitSegPat::DiscardInt(opt) => {
                        out.push('_');
                        out.push(':');
                        out.push_str(&fmt_int_opt(opt));
                    }
                    BitSegPat::Bytes => out.push_str("_:bytes"),
                }
            }
            out.push_str(">>");
        }
    }
}

fn write_guard(out: &mut String, e: &Expr, types: &[CustomType], ind: usize) {
    match e {
        Expr::Bin(op, l, r) => {
            write_guard(out, l, types, ind);
            out.push(' ');
            out.push_str(binop_str(*op));
            out.push(' ');
            write_guard(out, r, types, ind);
        }
        Expr::NegBool(x) => {
            out.push('!');
            write_guard(out, x, types, ind);
        }
        _ => write_expr(out, e, types, ind),
    }
}

fn fmt_int_opt(opt: &IntOpt) -> String {
    let endian = if opt.big { "big" } else { "little" };
    let sign = if opt.signed { "signed" } else { "unsigned" };
    format!("{}-{}-{}", endian, sign, opt.width)
}

fn push_indent(out: &mut String, ind: usize) {
    out.push('\n');
    for _ in 0..ind {
        out.push_str("  ");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::probe::ProbeOutcome;

    #[test]
    fn determinism() {
        for seed in [0u64, 1, 2, 42, 123_456_789] {
            assert_eq!(
                Module::from_seed(seed).to_source(),
                Module::from_seed(seed).to_source()
            );
        }
    }

    #[test]
    #[ignore = "manual artifact replay helper"]
    fn replay_artifact() {
        let path = std::env::var("FUZZING_ARTIFACT").expect("set FUZZING_ARTIFACT");
        let data = std::fs::read(&path).expect("read artifact");
        let mut u = Unstructured::new(&data);
        let module = Module::arbitrary(&mut u).expect("artifact decodes");
        let src = module.to_source();
        println!("--- generated source:\n{src}");
        match crate::probe::probe_guarded(src.as_bytes()) {
            Ok(outcome) => println!("--- outcome: {outcome}"),
            Err(panic) => {
                println!("--- guarded panic: {panic}");
            }
        }
    }

    /// Every generated program must parse and type check on both targets
    /// and reach code generation.
    #[test]
    fn generated_programs_compile_0_to_300() {
        for seed in 0..300u64 {
            let module = Module::from_seed(seed);
            let src = module.to_source();
            match crate::probe::probe_guarded(src.as_bytes()) {
                Ok(ProbeOutcome::Compiled { .. }) => {}
                Ok(outcome) => panic!(
                    "seed {seed} produced non-compiling program (outcome: {outcome}):\n{src}"
                ),
                Err(panic) => {
                    panic!("seed {seed} produced program that crashed the compiler: {panic}\n{src}")
                }
            }
        }
    }
}
