# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Gleam contributors

[package]
name = "native-ir"
authors = ["Ivan Kachalkin <xikxp1@gmail.com>"]
version = "1.0.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
serde.workspace = true
bitcode = { version = "0.6", features = ["serde"] }
