# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Gleam contributors

[package]
name = "native-runtime-static"
authors = ["Ivan Kachalkin <xikxp1@gmail.com>"]
version = "1.0.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
native-runtime = { path = "../native-runtime" }
